### ISSUE TITLE
shaka - `UbiquityDollarToken` allows users to transfer tokens to themselves and receive incentives both as sender and recipient

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-ubiquity-judging#8]
shaka

medium

# `UbiquityDollarToken` allows users to transfer tokens to themselves and receive incentives both as sender and recipient

## Summary

`UbiquityDollarToken` allows users to transfer tokens to themselves and receive incentives both as sender and recipient.

## Vulnerability Detail

`UbiquityDollarToken` transfers applies optional incentives to the sender, recipient and operator. This is performed in the `_checkAndApplyIncentives` internal function.

While there is a check to ensure that the operator is a different address than the sender and recipient, there is no check to ensure that the sender and recipient are different addresses. This means that if the sender and recipient are the same address, the incentives will be applied twice to the same address. 

While the transfer does not have any impact on the balance of the user, he will receive incentives both as sender and recipient.

## Impact

Users can transfer tokens to themselves and receive extra incentives without any impact on their balance.

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/core/UbiquityDollarToken.sol#L84-L136

## Tool used

Manual Review

## Recommendation

```diff
    function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal override {
        super._transfer(sender, recipient, amount);
-       _checkAndApplyIncentives(sender, recipient, amount);
+       if (sender != recipient) {
+           _checkAndApplyIncentives(sender, recipient, amount);
+       }
    }
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xLogos** commented:
> i think it's intended to incentivise liquidity provision, not regular transfers

**Comment by osmanozdemir1** [comment]
Escalate

1. As the lead judge said, we can not know how the OOS incentive contract works and we should not assume that OOS incentive contract will perform all necessary checks. Besides, the fact that there is a [specific check for operators](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/core/UbiquityDollarToken.sol#L114C13-L116C44) gives the idea of that OOS incentive contract may not be performing necessary checks.

2. > In fact based one incentivization contract I observe has the relevant [check seen here](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibCurveDollarIncentive.sol#L82)

The example contract the judge provided here takes 3 arguments but the actual code calls `incentivize` function with 4 arguments. They are not the same and we can't know there will be a check.

3. Whitelist alone will not be a solution. One whitelisted address can transfer itself and still get incentivized. 
Whitelist without `sender != recipient` check can only prevent users to create new accounts and transfer between but not prevent self-transfer.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> 1. As the lead judge said, we can not know how the OOS incentive contract works and we should not assume that OOS incentive contract will perform all necessary checks. Besides, the fact that there is a [specific check for operators](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/core/UbiquityDollarToken.sol#L114C13-L116C44) gives the idea of that OOS incentive contract may not be performing necessary checks.
> 
> 2. > In fact based one incentivization contract I observe has the relevant [check seen here](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibCurveDollarIncentive.sol#L82)
> 
> The example contract the judge provided here takes 3 arguments but the actual code calls `incentivize` function with 4 arguments. They are not the same and we can't know there will be a check.
> 
> 3. Whitelist alone will not be a solution. One whitelisted address can transfer itself and still get incentivized. 
> Whitelist without `sender != recipient` check can only prevent users to create new accounts and transfer between but not prevent self-transfer.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by shaka0x** [comment]
I do agree with @osmanozdemir1 comments. Specially, the fact that the function contains a similar check for operator not being sender or receiver suggests that this other other check (sender is not also receiver) should also have been added in the contract.

I would also like to point that, as far as I understand, according to Sherlock's rules, the fact that the team will fix the issue using an approach different from the one suggested in the report should not be a reason for invalidating it.

**Comment by nevillehuang** [comment]
See comments [here](https://discord.com/channels/812037309376495636/1191764748216303776/1200385007814975589) as well @Czar102 commenting on a similar type of issue [here](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/281#issuecomment-1858542154). I believe no further inputs is required from my side.

**Comment by 0xunforgiven** [comment]
I do agree with @osmanozdemir1 too. 

I believe the 3 thing lead judge mentioned in the above [comment](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/8#issuecomment-1904044222) is wrong, because:
1- doc says (incentive) is a multi purpose feature and it's possible to know the intended behavior (from `operator != sender` and sponsor validating bug). 
2- the reports shows exactly that the bug is in-scope contract and the assumption that it's in the `IIncentive.sol` or its implementations is wrong. 
3- the incentive function that lead judge said has checks in it, is totally another incentive function(3 argument) and it's not related to this one(which has 4 arguments). it's just a simple name collision.
4- there is an incentive address association for sender, recipient and operator incentive calls which work as whitelist and controlled by admin. the duplicate of this report like #211 shows that recipient incentive call doesn't have validation and it cause duplicate incentive calling.


what we know from the docs is that, incentive is multipurpose feature. we know also code have some checks to prevent calling incentive for operator and sender/receiver if they are equal.


I agree that the whole purpose of the incentive and its usage is not clear in the contest. but that doesn't mean that code is not wrong. this is the nature of partial-protocol audits. some part of protocol logics are out of scope and they aren't included in the contest repo. In these cases and similar cases we need to rely on sponsor comments as they know the whole project and they know what they wanted to implement and they can confirm if something is bug.


As Final note, The issue here is not that some one can create multiple EOA account and transfer token between his accounts. so I don't believe [comment](https://discord.com/channels/812037309376495636/1191764748216303776/1200385007814975589) apply here and this is not similar issue. here we have missing validation checks that could cause double spending and double calculation and .... (based on incentive feature usage) and clearly developers wanted to avoid it (`operator != sender` check)

There is more discussion about this issue in the [discord](https://discord.com/channels/812037309376495636/1191764748216303776/1200361070045433916) channel.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep invalid.

As the incentive contract is out of scope, it's unclear how the following logic can lead to a loss of funds.

> _checkAndApplyIncentives(sender, recipient, amount);

Although the protocol team aims to make changes to the codebase based on this issue, as they know how the logic of the incentive contract works. It would be unfair to reward this report as competitors were not expected to know about the logic of the incentive contract (out of scope).

**Comment by molecula451** [comment]
the suggestion fix looks ugly, we added a `require()` instead

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- Expected issue to not have any duplicates. Existing duplicates: #66, #129, #155, #211

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/ubiquity/ubiquity-dollar/pull/875.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed off on the fix.
